<Project>
  <PropertyGroup>
    <VersionPrefix>2026.5.3</VersionPrefix>
    <Version Condition="'$(Version)' == ''">$(VersionPrefix)</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(VersionPrefix)</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(VersionPrefix)</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
    <Company>SI360</Company>
    <Product>SI360 GateRunner</Product>
    <Authors>SI360</Authors>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
