using System.Globalization;
using System.IO;
using System.Text;
using System.Text.Json;
using SI360.GateRunner.Models;
using SI360.GateRunner.ViewModels;

namespace SI360.GateRunner.Services;

public sealed class ReportWriter
{
    public async Task<(string MarkdownPath, string JsonPath)> WriteAsync(RunSummary summary, string outputDir)
    {
        Directory.CreateDirectory(outputDir);
        var ts = summary.StartedAt.ToString("yyyyMMdd_HHmmss", CultureInfo.InvariantCulture);
        var mdPath = Path.Combine(outputDir, $"GateRun_{ts}.md");
        var jsonPath = Path.Combine(outputDir, $"GateRun_{ts}.json");

        await File.WriteAllTextAsync(mdPath, BuildMarkdown(summary), Encoding.UTF8);
        await File.WriteAllTextAsync(jsonPath, BuildJson(summary), Encoding.UTF8);
        return (mdPath, jsonPath);
    }

    private static string BuildMarkdown(RunSummary s)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# SI360 Pre-Deployment Gate Run — {s.StartedAt:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine($"**Duration:** {s.Duration.TotalSeconds:0.0}s  ");
        sb.AppendLine($"**Decision:** **{Label(s.Decision)}**  ");
        sb.AppendLine($"**Overall Score:** {s.Scorecard.OverallScore:0.00} ({s.Scorecard.Grade})  ");
        sb.AppendLine($"**Scenario:** {s.Scorecard.ScenarioScore:0.0} / 100 &nbsp;&nbsp; **Probabilistic:** {s.Scorecard.ProbabilisticScore:0.0} / 100");
        sb.AppendLine();

        if (s.BuildErrors.Count > 0)
        {
            sb.AppendLine("## Build Errors");
            sb.AppendLine();
            sb.AppendLine("| File | Line | Code | Message |");
            sb.AppendLine("|------|-----:|------|---------|");
            foreach (var e in s.BuildErrors)
                sb.AppendLine($"| `{Escape(e.FilePath)}` | {e.Line} | {e.Code} | {Escape(e.Message)} |");
            sb.AppendLine();
        }

        sb.AppendLine("## Gates");
        sb.AppendLine();
        sb.AppendLine("| # | Gate | Status | Passed | Failed | Skipped | Duration |");
        sb.AppendLine("|---|------|--------|-------:|-------:|--------:|---------:|");
        var i = 1;
        foreach (var g in s.GateResults)
        {
            sb.AppendLine($"| {i++} | {g.Definition.DisplayName} | {g.Status} | {g.Passed} | {g.Failed} | {g.Skipped} | {g.Duration.TotalSeconds:0.0}s |");
        }
        sb.AppendLine();

        sb.AppendLine("## Satisfaction Scorecard");
        sb.AppendLine();
        sb.AppendLine("### Scenarios (weight-based)");
        sb.AppendLine();
        sb.AppendLine("| Scenario | Weight | Result |");
        sb.AppendLine("|----------|-------:|--------|");
        foreach (var sc in s.Scorecard.Scenarios)
            sb.AppendLine($"| {sc.Name} | {sc.Weight} | {(sc.Passed ? "PASS" : "FAIL")} |");
        sb.AppendLine();
        sb.AppendLine("### Probabilistic");
        sb.AppendLine();
        sb.AppendLine("| Suite | Success Rate | Score | P95 (ms) |");
        sb.AppendLine("|-------|-------------:|------:|---------:|");
        foreach (var p in s.Scorecard.Probabilistics)
            sb.AppendLine($"| {p.Name} | {p.SuccessRatePct:0.0}% | {p.Score} | {(p.P95Ms?.ToString("0.0") ?? "—")} |");
        sb.AppendLine();

        var failures = s.GateResults
            .SelectMany(g => g.Outcomes.Where(o => o.Status == TestStatus.Failed))
            .ToList();
        if (failures.Count > 0)
        {
            sb.AppendLine($"## Failure Inventory ({failures.Count})");
            sb.AppendLine();
            var n = 1;
            foreach (var f in failures)
            {
                var item = FailureItemViewModel.From(f);
                sb.AppendLine($"### {n++}. `{item.TestName}`");
                sb.AppendLine($"- **Gate:** {item.GateName}");
                sb.AppendLine($"- **Failure Type:** {item.FailureType}");
                sb.AppendLine($"- **Error Message:** `{Escape(item.ErrorMessage)}`");
                var loc = item.FilePath is null ? "—" : $"`{item.FilePath}:{item.LineNumber}`";
                sb.AppendLine($"- **File/Component:** {loc} → `{item.ComponentHint}`");
                sb.AppendLine();
            }
        }

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("*Generated by SI360.GateRunner.*");
        return sb.ToString();
    }

    private static string BuildJson(RunSummary s)
    {
        var dto = new
        {
            startedAt = s.StartedAt,
            durationSeconds = s.Duration.TotalSeconds,
            decision = Label(s.Decision),
            scorecard = new
            {
                scenarioScore = s.Scorecard.ScenarioScore,
                probabilisticScore = s.Scorecard.ProbabilisticScore,
                overallScore = s.Scorecard.OverallScore,
                grade = s.Scorecard.Grade,
                scenarios = s.Scorecard.Scenarios,
                probabilistics = s.Scorecard.Probabilistics
            },
            buildErrors = s.BuildErrors,
            gates = s.GateResults.Select(g => new
            {
                id = g.Definition.Id,
                name = g.Definition.DisplayName,
                status = g.Status.ToString(),
                passed = g.Passed,
                failed = g.Failed,
                skipped = g.Skipped,
                durationSeconds = g.Duration.TotalSeconds,
                trxPath = g.TrxPath,
                errorMessage = g.ErrorMessage,
                failures = g.Outcomes.Where(o => o.Status == TestStatus.Failed).Select(o => new
                {
                    o.TestName,
                    o.ErrorMessage,
                    o.FilePath,
                    o.LineNumber,
                    o.StackTrace
                })
            })
        };
        return JsonSerializer.Serialize(dto, new JsonSerializerOptions { WriteIndented = true });
    }

    private static string Label(DeployDecision d) => d switch
    {
        DeployDecision.Go => "GO",
        DeployDecision.Hold => "HOLD",
        _ => "NO-GO"
    };

    private static string Escape(string s) =>
        s.Replace("|", "\\|").Replace("`", "\\`").Replace("\r", " ").Replace("\n", " ");
}
