using SI360.GateRunner.Models;

namespace SI360.GateRunner.Services;

public static class GateCatalog
{
    public static IReadOnlyList<GateDefinition> All { get; } = new[]
    {
        new GateDefinition("BuildGate", "Build Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.BuildGateTests",
            17, GateCategory.Build,
            "Assembly loading, DI registration, interface contracts."),
        new GateDefinition("CICDPipelineGate", "CI/CD Pipeline Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.CICDPipelineGateTests",
            75, GateCategory.Pipeline,
            "Pipeline YAML, quality gates, CI stages."),
        new GateDefinition("DataIntegrityGate", "Data Integrity Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.DataIntegrityGateTests",
            21, GateCategory.Data,
            "Schema, referential integrity, idempotency."),
        new GateDefinition("Phase1FoundationGate", "Phase 1 Foundation Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.Phase1FoundationGateTests",
            48, GateCategory.Foundation,
            "DB clone factory, failover surface (ConnectedToPosDb, IsSiteDbReachableAsync)."),
        new GateDefinition("Phase2MonitoringGate", "Phase 2 Monitoring Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.Phase2MonitoringGateTests",
            50, GateCategory.Monitoring,
            "Health monitor, telemetry, logging."),
        new GateDefinition("Phase3CoverageGate", "Phase 3 Coverage Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.Phase3CoverageGateTests",
            48, GateCategory.Coverage,
            "Coverage thresholds, rollback dual-DB support."),
        new GateDefinition("Phase4ScaleGate", "Phase 4 Scale Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.Phase4ScaleGateTests",
            43, GateCategory.Scale,
            "Scale, connection factory cache, async patterns."),
        new GateDefinition("PreDeploymentGate", "Pre-Deployment Orchestrator",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.PreDeploymentGateTests",
            1, GateCategory.Orchestrator,
            "Orchestrator: runs 5 scenarios + 5 probabilistic; fails when composite < 95."),
        new GateDefinition("ProductionMonitoringGate", "Production Monitoring Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.ProductionMonitoringGateTests",
            44, GateCategory.Production,
            "Runtime alerting + Serilog sinks."),
        new GateDefinition("ProductionSafetyGate", "Production Safety Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.ProductionSafetyGateTests",
            40, GateCategory.Safety,
            "Payment test mocking, secrets, PCI."),
        new GateDefinition("SatisfactionScorecardThreshold", "Satisfaction Scorecard Threshold",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.SatisfactionScorecardThresholdTests",
            49, GateCategory.Scorecard,
            "Composite formula, grade boundaries, GO/HOLD/NO-GO."),
        new GateDefinition("ScenarioWeightGate", "Scenario Weight Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.ScenarioWeightGateTests",
            35, GateCategory.ScenarioWeights,
            "Scenario weights sum to 100, integrity."),
        new GateDefinition("SecurityGate", "Security Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.SecurityGateTests",
            28, GateCategory.Security,
            "PCI masking, password hashing, SQL safety."),
        new GateDefinition("StagedRolloutGate", "Staged Rollout Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.StagedRolloutGateTests",
            37, GateCategory.StagedRollout,
            "Canary, rollback plan, blue/green."),
        new GateDefinition("TestInventoryGate", "Test Inventory Gate",
            "FullyQualifiedName~SI360.Tests.PreDeploymentGate.TestInventoryGateTests",
            38, GateCategory.TestInventory,
            "Total test count >= threshold, class count thresholds.")
    };
}
